name: build
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      forceRelease:
        description: 'Create a new release'
        required: false
        default: false
        type: boolean
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm t
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job,took
        if: always()

  release:
    needs: test
    if: inputs.forceRelease || startsWith(github.event.head_commit.message, 'release v')
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run release
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,job,took
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
